on: [push, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: A job to publish package
    steps:
      - uses: actions/checkout@v2
      - name: Pack and publish
        id: pnp
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/HelloWorldLibrary/HelloWroldLibrary.csproj
          PACKAGE_NAME: HelloWorldLibrary
