on: [push, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: A job to publish package
    steps:
      - uses: actions/checkout@v2
      - name: Pack and publish
        id: pnp
        uses: medegor44/publish-nuget@v2
        with:
          PROJECTS_DIR: 'src'
